x-var: &PHP_IMAGE
  php:7.4.16-apache
services:
  php-projectName:
    platform: linux/x86_64
    image: *PHP_IMAGE
    volumes:
      - ./docker/php:/usr/local/etc/php
      - ./docker/sites-available:/etc/apache2/sites-available
      - ./:/var/www/html
    build:
      context: ./docker/
      dockerfile: Dockerfile
      args:
        PHP_IMAGE: *PHP_IMAGE
    ports:
      - 8080:80
    depends_on:
      - mysql-projectName
  mysql-projectName:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin-projectName:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-projectName
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql-projectName
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions