services:
  php:
    platform: linux/x86_64
    image: php:7.4.16-apache
    volumes:
      - ./docker/php:/usr/local/etc/php
      - ./docker/sites-available:/etc/apache2/sites-available
      - ./:/var/www/html
    ports:
      - 8080:80
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions